base_url = "https://Karthik-d-k.github.io"
description = "Personal Blog"
compile_sass = false
minify_html = true
generate_feed = true
default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = true
highlight_theme = "solarized-light"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Speyll"
display_author = true

favicon = "favicon.ico"
image = ""

default_theme = "light"
list_pages = false
twitter_card = true

header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/about", name_en = "/about/" },
  { url = "/blog", name_en = "/blog/" },
  { url = "/bookmarks", name_en = "/bookmarks/" }
]
